const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Content-Type":"application/json"};
const APINEX_BASE="https://api.apinex.bond/v1";
const OPENROUTER_BASE="https://openrouter.ai/api/v1";
const APPMIX_BASE="https://api.apmix.ai/v1";
const VERSION=20;

function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:cors})}
function replyFrom(d:any){const c=d?.choices?.[0]?.message?.content;if(typeof c==="string")return c.trim();if(Array.isArray(c))return c.map((x:any)=>typeof x==="string"?x:x?.text||"").join("").trim();return ""}
function cleanMessages(v:unknown){if(!Array.isArray(v))return[];return v.slice(-16).map((m:any)=>({role:["assistant","system"].includes(m?.role)?m.role:"user",content:String(m?.content||"").slice(0,16000)})).filter((m:any)=>m.content)}
async function fetchJson(url:string,init:RequestInit,ms:number){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{...init,signal:c.signal});const raw=await r.text();let d:any={};try{d=JSON.parse(raw)}catch{d={error:{message:raw}}}return{r,d}}finally{clearTimeout(t)}}
function safeErr(e:unknown){const s=String((e as Error)?.message||e||"");if(/abort|timeout|timed out/i.test(s))return "timeout";if(/401|unauthor|invalid api|invalid key|key_expired/i.test(s))return "unauthorized";if(/429|rate|quota|allowance|limit/i.test(s))return "rate_limited";if(/model.*not.*found|unknown model|retired model/i.test(s))return "model_unavailable";return s.replace(/Bearer\s+\S+/gi,"Bearer [redacted]").slice(0,180)||"failed"}
async function callProvider(url:string,key:string,model:string,messages:any[],headers:Record<string,string>={},timeout=9000,maxTokens=1200){const {r,d}=await fetchJson(url,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json",...headers},body:JSON.stringify({model,messages,max_tokens:maxTokens,temperature:.3})},timeout);if(!r.ok)throw new Error(d?.error?.message||d?.message||`HTTP ${r.status}`);const reply=replyFrom(d);if(!reply)throw new Error("empty response");return reply}
function modelIds(d:any){const raw=Array.isArray(d)?d:Array.isArray(d?.data)?d.data:Array.isArray(d?.models)?d.models:Array.isArray(d?.result)?d.result:[];return raw.map((x:any)=>typeof x==="string"?x:String(x?.id||x?.model||x?.name||"")).filter(Boolean)}
async function listModels(base:string,key:string,timeout=3500){const {r,d}=await fetchJson(`${base}/models`,{headers:{Authorization:`Bearer ${key}`}},timeout);if(!r.ok)throw new Error(d?.error?.message||d?.message||`HTTP ${r.status}`);return modelIds(d)}
async function firstWorking(models:string[],run:(model:string)=>Promise<string>,provider:string){let last="no_models";for(const model of models){try{return{reply:await run(model),provider:`${provider}:${model}`}}catch(e){last=safeErr(e);if(last==="rate_limited"||last==="unauthorized"||last==="timeout")break}}throw new Error(last)}
async function apinexGroup(key:string,prompt:any[]){const models=(await listModels(APINEX_BASE,key)).filter((id:string)=>id.startsWith("free/")).slice(0,4);if(!models.length)throw new Error("no_free_models");return firstWorking(models,m=>callProvider(`${APINEX_BASE}/chat/completions`,key,m,prompt,{},8000),"apinex")}
async function appmixGroup(key:string,prompt:any[]){const all=await listModels(APPMIX_BASE,key);const free=all.filter((id:string)=>/-free(?:$|\b)/i.test(id)||/free/i.test(id));const models=(free.length?free:all).slice(0,5);if(!models.length)throw new Error("no_models_returned");return firstWorking(models,m=>callProvider(`${APPMIX_BASE}/chat/completions`,key,m,prompt,{},8500),"appmix")}
async function openrouterJob(key:string,prompt:any[]){const reply=await callProvider(`${OPENROUTER_BASE}/chat/completions`,key,"openrouter/free",prompt,{"HTTP-Referer":"https://ai.tivalsdeveloper.site/","X-OpenRouter-Title":"Tivals AI"},8500);return{reply,provider:"openrouter:free"}}
async function probe(name:string,fn:()=>Promise<any>){const started=Date.now();try{const value=await fn();return{name,ok:true,latency_ms:Date.now()-started,detail:value}}catch(e){return{name,ok:false,latency_ms:Date.now()-started,error:safeErr(e)}}}
async function health(apinex:string,open:string,app:string){const tiny=[{role:"system",content:"Reply exactly OK."},{role:"user",content:"OK"}];const tests:Promise<any>[]=[];
 if(apinex)tests.push(probe("Apinex",async()=>{const models=(await listModels(APINEX_BASE,apinex,3000)).filter((id:string)=>id.startsWith("free/")).slice(0,1);if(!models.length)throw new Error("no_free_models");await callProvider(`${APINEX_BASE}/chat/completions`,apinex,models[0],tiny,{},4500,12);return{model:models[0]}}));else tests.push(Promise.resolve({name:"Apinex",ok:false,error:"not_configured"}));
 if(open)tests.push(probe("OpenRouter",async()=>{await callProvider(`${OPENROUTER_BASE}/chat/completions`,open,"openrouter/free",tiny,{"HTTP-Referer":"https://ai.tivalsdeveloper.site/","X-OpenRouter-Title":"Tivals AI"},4500,12);return{model:"openrouter/free"}}));else tests.push(Promise.resolve({name:"OpenRouter",ok:false,error:"not_configured"}));
 if(app)tests.push(probe("AppMix",async()=>{const all=await listModels(APPMIX_BASE,app,3000);const free=all.filter((id:string)=>/-free(?:$|\b)/i.test(id)||/free/i.test(id));const models=(free.length?free:all).slice(0,1);if(!models.length)throw new Error("no_models_returned");await callProvider(`${APPMIX_BASE}/chat/completions`,app,models[0],tiny,{},5000,12);return{model:models[0],models_visible:all.length}}));else tests.push(Promise.resolve({name:"AppMix",ok:false,error:"not_configured"}));
 return Promise.all(tests)}

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});
 const apinex=Deno.env.get("APINEX_API_KEY")||"",open=Deno.env.get("OPENROUTER_API_KEY")||"",app=Deno.env.get("APPMIX_API_KEY")||"";
 if(req.method==="GET"){const u=new URL(req.url);if(u.searchParams.get("health")==="1"){const providers=await health(apinex,open,app);return json({ok:providers.some((p:any)=>p.ok),service:"tivals-ai-chat",version:VERSION,configured:{apinex:!!apinex,openrouter:!!open,appmix:!!app},providers})}return json({ok:true,service:"tivals-ai-chat",version:VERSION,dynamic_models:true,provider_level_racing:true,configured_providers:[...(apinex?["Apinex"]:[]),...(open?["OpenRouter"]:[]),...(app?["AppMix"]:[])]})}
 if(req.method!=="POST")return json({error:"Method not allowed."},405);
 let body:any;try{body=await req.json()}catch{return json({error:"Invalid JSON request."},400)}
 const messages=cleanMessages(body?.messages);if(!messages.length&&body?.message)messages.push({role:"user",content:String(body.message).slice(0,16000)});if(!messages.length)return json({error:"Please enter a message."},400);
 const system={role:"system",content:"You are Tivals AI, a capable general-purpose assistant. Give accurate, direct, phone-friendly answers. Use Markdown. For learning requests, teach one focused lesson at a time and include a short practice task."};
 const prompt=[system,...messages.filter((m:any)=>m.role!=="system")];const jobs:Promise<{reply:string,provider:string}>[]=[];
 if(apinex)jobs.push(apinexGroup(apinex,prompt));if(open)jobs.push(openrouterJob(open,prompt));if(app)jobs.push(appmixGroup(app,prompt));
 if(!jobs.length)return json({error:"Tivals AI is not configured.",code:"NO_PROVIDER_KEYS"},503);
 try{const winner=await Promise.any(jobs);return json({reply:winner.reply,model:"tivals-ai",provider:"Tivals AI",route:winner.provider})}catch{return json({error:"All configured AI providers are currently unavailable or rate-limited. Please try again shortly.",code:"ALL_PROVIDERS_FAILED"},502)}
});