/* Tivals AI radio hub — in-app playback, chat commands and playback notifications. */
(()=>{
const stations=[
{name:'Phalaphala FM',aliases:['phalaphala'],lang:'Tshivenda',stream:'https://playerservices.streamtheworld.com/api/livestream-redirect/PHALAPHALAAAC.aac?dist=tivalsai',url:'https://www.phalaphalafm.co.za/phalaphalafm/'},
{name:'Thobela FM',aliases:['thobela'],lang:'Sepedi',stream:'https://playerservices.streamtheworld.com/api/livestream-redirect/THOBELAAAC_SC?dist=tivalsai',url:'https://www.thobelafm.co.za/thobelafm/livestreams/'},
{name:'METRO FM',aliases:['metro'],lang:'Music / English',url:'https://www.metrofm.co.za/metro-fm/listen-live/'},
{name:'Ukhozi FM',aliases:['ukhozi'],lang:'isiZulu',stream:'https://playerservices.streamtheworld.com/api/livestream-redirect/UKHOZIFMAAC_SC?dist=tivalsai',url:'https://www.ukhozifm.co.za/'},
{name:'5FM',aliases:['5 fm','five fm'],lang:'Youth / Music',url:'https://listen.5fm.co.za/'},
{name:'Munghana Lonene FM',aliases:['munghana','munghana lonene'],lang:'itsonga',url:'https://listen.munghanalonenefm.co.za/listenmunghanalonenefm/'},
{name:'Motsweding FM',aliases:['motsweding'],lang:'Setswana',url:'https://listen.motswedingfm.co.za/listenmotswedingfm/'},
{name:'Lesedi FM',aliases:['lesedi'],lang:'Sesotho',stream:'https://playerservices.streamtheworld.com/api/livestream-redirect/LESEDIAAC_SC?dist=tivalsai',url:'https://www.lesedifm.co.za/lesedifm/'},
{name:'SAfm',aliases:['sa fm','safm'],lang:'News / Talk',url:'https://www.safm.co.za/'},{name:'Radio 2000',aliases:['radio 2000'],lang:'Music / Talk',url:'https://www.radio2000.co.za/'},{name:'Good Hope FM',aliases:['good hope'],lang:'Music',url:'https://www.goodhopefm.co.za/'},{name:'Umhlobo Wenene FM',aliases:['umhlobo','umhlobo wenene'],lang:'isiXhosa',url:'https://www.umhlobowenenefm.co.za/'},{name:'Ligwalagwala FM',aliases:['ligwalagwala'],lang:'siSwati',url:'https://www.ligwalagwalafm.co.za/'},{name:'Ikwekwezi FM',aliases:['ikwekwezi'],lang:'isiNdebele',url:'https://www.ikwekwezifm.co.za/'},{name:'Lotus FM',aliases:['lotus'],lang:'Indian South African',url:'https://www.lotusfm.co.za/'},{name:'RSG',aliases:['rsg'],lang:'Afrikaans',url:'https://www.rsg.co.za/'},
{name:'Jacaranda FM',aliases:['jacaranda'],lang:'English / Afrikaans',stream:'https://edge.iono.fm/xice/jacarandafm_live_medium.aac',url:'https://www.jacarandafm.com/'},{name:'Power 98.7',aliases:['power','power 98.7'],lang:'English / Talk',stream:'https://edge.iono.fm/xice/65_medium.aac',url:'https://www.power987.co.za/'},{name:'KFM 94.5',aliases:['kfm','kfm 94.5'],lang:'English / Music',stream:'https://playerservices.streamtheworld.com/api/livestream-redirect/KFM.mp3?dist=tivalsai',url:'https://kfm.co.za/'},
{name:'East Coast Radio',aliases:['east coast','ecr','east coast radio'],lang:'English / Music',stream:'https://edge.iono.fm/xice/ecr_live_medium.aac',url:'https://www.ecr.co.za/listen-live/'}];
let audio=new Audio(),current=null;audio.preload='none';
const css=`#tivalsRadio{position:fixed;inset:0;z-index:10050;background:#061a31;color:#f7fbff;display:none;overflow:auto;font-family:inherit}.tr-head{position:sticky;top:0;z-index:2;background:#092542;padding:16px;display:flex;align-items:center;gap:12px;border-bottom:1px solid #24517b}.tr-head h2{margin:0;flex:1;display:flex;align-items:center;gap:10px}.tr-brand-icon{width:34px;height:34px;border-radius:10px;display:block;box-shadow:0 4px 12px #0005}.tr-grid{padding-bottom:170px}.tr-close{border:1px solid #3d6b96;background:#102f50;color:white;border-radius:12px;padding:10px 14px;font-size:20px}.tr-search{display:block;width:calc(100% - 32px);box-sizing:border-box;margin:16px;padding:13px 15px;border-radius:14px;border:1px solid #315e87;background:#0b2744;color:white;font-size:16px}.tr-grid{padding:0 16px 130px;display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.tr-card{border:1px solid #214b70;background:#0a233e;border-radius:16px;padding:15px}.tr-card h3{margin:0 0 5px}.tr-card small{opacity:.72}.tr-play{margin-top:13px;width:100%;border:0;border-radius:12px;padding:12px;background:#1677d2;color:white;font-weight:700}.tr-now{position:fixed;z-index:10051;left:12px;right:12px;bottom:12px;background:#0d2d4c;border:1px solid #376b96;border-radius:18px;padding:12px;display:none;align-items:center;gap:10px}.tr-now strong{flex:1}.tr-now button{border:0;border-radius:10px;padding:10px 13px;background:#1677d2;color:#fff}.tr-toast{position:fixed;z-index:11000;left:16px;right:16px;bottom:112px;max-width:none;background:#0d2d4c;color:#fff;border:1px solid #4381b5;border-radius:14px;padding:10px 14px;box-shadow:0 8px 30px #0008;display:none;text-align:center;font-weight:700;pointer-events:none}.tr-note{padding:0 16px 14px;opacity:.75;font-size:13px}`;
function toast(text){text=String(text||'').replace(/^📻\s*/,'');let n=document.querySelector('#tivalsRadioToast');if(!n){n=document.createElement('div');n.id='tivalsRadioToast';n.className='tr-toast';document.body.appendChild(n)}n.textContent=text;n.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>n.style.display='none',3500)}
function notify(s){toast('Now playing: '+s.name);if('Notification'in window&&Notification.permission==='granted'){try{new Notification('Tivals AI Radio',{body:'Now playing '+s.name,icon:'app-icon.svg',tag:'tivals-radio'})}catch{}}}
function fallback(s){toast('📻 Direct stream unavailable — opening '+s.name+' live player');const w=window.open(s.url,'_blank','noopener,noreferrer');if(!w)location.href=s.url}
async function play(s){if(!s)return;if(!s.stream){fallback(s);return}try{audio.pause();audio.src=s.stream;audio.load();current=s;await audio.play();updateNow();render(document.querySelector('#tivalsRadioSearch')?.value||'');notify(s)}catch(e){console.warn('Radio stream failed',e);audio.pause();audio.removeAttribute('src');audio.load();current=null;updateNow();render(document.querySelector('#tivalsRadioSearch')?.value||'');fallback(s)}}
function stop(){audio.pause();audio.removeAttribute('src');audio.load();const old=current;current=null;updateNow();render(document.querySelector('#tivalsRadioSearch')?.value||'');if(old)toast('Radio stopped')}
function updateNow(){const n=document.querySelector('#tivalsRadioNow');if(!n)return;n.style.display=current?'flex':'none';const t=n.querySelector('strong');if(t)t.textContent=current?current.name+(audio.paused?' · Paused':' · Playing'):''}
function findStation(text){const q=String(text||'').toLowerCase().replace(/[^a-z0-9. ]/g,' ').replace(/\s+/g,' ').trim();return stations.find(s=>[s.name,...(s.aliases||[])].some(a=>q.includes(a.toLowerCase())))}
function radioIntent(text){const q=String(text||'').trim().toLowerCase();if(!q)return null;if(/^(?:open|show)?\s*radio\s*$/.test(q)||/^(?:radio stations|show radio stations|list radio stations)$/.test(q))return{action:'open'};if(/^(?:stop|turn off|switch off|pause)\s+(?:the\s+)?radio\b/.test(q)||/^(?:stop|pause)\s*$/.test(q)&&current)return{action:q.startsWith('pause')?'pause':'stop'};if(/^(?:resume|continue)\s+(?:the\s+)?radio\b/.test(q))return{action:'resume'};if(/\b(?:play|listen to|start|stream|put on)\b/.test(q)&&(/\bradio\b/.test(q)||findStation(q)))return{action:'play',station:findStation(q)};if(/^radio\s+.+/.test(q))return{action:'play',station:findStation(q)};return null}
function chatReply(text){try{if(typeof window.add==='function'){window.add('ai',text);return}}catch{}toast(text)}
async function handleChat(text){const i=radioIntent(text);if(!i)return false;if(i.action==='open'){open();chatReply('Radio is open. Choose a station or type “play Phalaphala FM”, “play East Coast Radio”, or another station name.');return true}if(i.action==='stop'){stop();chatReply('⏹ Radio stopped.');return true}if(i.action==='pause'){audio.pause();updateNow();chatReply('⏸ Radio paused.');return true}if(i.action==='resume'){if(current){await audio.play().catch(()=>{});updateNow();chatReply('▶ Resumed '+current.name+'.')}else{open();chatReply('No station is currently selected. Choose a radio station.')}return true}if(i.action==='play'){if(!i.station){open();chatReply('📻 Which station should I play? You can choose a station from the Radio list.');return true}await play(i.station);chatReply('Playing '+i.station.name+' directly in Tivals AI.');return true}return false}
function intercept(){document.addEventListener('submit',async e=>{const form=e.target;if(!(form instanceof HTMLFormElement))return;const ta=form.querySelector('textarea');if(!ta)return;const text=ta.value;if(!radioIntent(text))return;e.preventDefault();e.stopImmediatePropagation();if(typeof window.add==='function')window.add('user',text);ta.value='';await handleChat(text)},true);document.addEventListener('keydown',async e=>{if(e.key!=='Enter'||e.shiftKey)return;const ta=e.target;if(!(ta instanceof HTMLTextAreaElement)||!radioIntent(ta.value))return;e.preventDefault();e.stopImmediatePropagation();const text=ta.value;if(typeof window.add==='function')window.add('user',text);ta.value='';await handleChat(text)},true)}
function render(q=''){const root=document.querySelector('#tivalsRadioGrid');if(!root)return;const x=q.trim().toLowerCase();root.innerHTML='';stations.filter(s=>!x||`${s.name} ${s.lang}`.toLowerCase().includes(x)).forEach(s=>{const c=document.createElement('div');c.className='tr-card';const h=document.createElement('h3');h.textContent=s.name;const sm=document.createElement('small');sm.textContent=s.lang+(s.stream?' · In-app live':' · Official live player');const b=document.createElement('button');b.className='tr-play';b.textContent=current?.name===s.name&&!audio.paused?'⏹ Stop':'▶ Listen Live';b.onclick=()=>current?.name===s.name&&!audio.paused?stop():play(s);c.append(h,sm,b);root.appendChild(c)})}
function open(){const p=document.querySelector('#tivalsRadio');if(p){p.style.display='block';render()}}function close(){const p=document.querySelector('#tivalsRadio');if(p)p.style.display='none'}
function boot(){if(document.querySelector('#tivalsRadio'))return;const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);const p=document.createElement('section');p.id='tivalsRadio';p.innerHTML='<div class="tr-head"><h2><img class="tr-brand-icon" src="app-icon.svg" alt="">Live Radio</h2><button class="tr-close">×</button></div><input class="tr-search" id="tivalsRadioSearch" placeholder="Search stations or language…"><div class="tr-note">Play radio here or type a command in chat, for example: “play East Coast Radio” or “radio”.</div><div class="tr-grid" id="tivalsRadioGrid"></div><div class="tr-now" id="tivalsRadioNow"><strong></strong><button id="trPause">⏯</button><button id="trStop">⏹</button></div>';document.body.appendChild(p);p.querySelector('.tr-close').onclick=close;p.querySelector('#tivalsRadioSearch').oninput=e=>render(e.target.value);p.querySelector('#trPause').onclick=()=>{if(audio.paused)audio.play();else audio.pause();updateNow()};p.querySelector('#trStop').onclick=stop;render();const host=document.querySelector('.sideTools')||document.querySelector('.tools')||document.querySelector('nav');if(host&&!document.querySelector('#tivalsRadioButton')){const b=document.createElement('button');b.type='button';b.id='tivalsRadioButton';b.className=host.classList.contains('sideTools')?'sideTool':'toolBtn';b.textContent='📻 Radio';b.onclick=open;host.appendChild(b)}intercept()}
audio.onplay=()=>{updateNow();render(document.querySelector('#tivalsRadioSearch')?.value||'')};audio.onpause=()=>{updateNow();render(document.querySelector('#tivalsRadioSearch')?.value||'')};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.TivalsRadio={open,close,stations,play,stop,audio,findStation,handleChat,radioIntent};
})();