/* Tivals AI — durable YouTube search messages rendered in chronological chat flow. */
(()=>{const END='https://kxuszpixwfecawdeqkrx.supabase.co/functions/v1/youtube-search',HIST='tivals-ai-history';
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function host(){return document.querySelector('#messages,.messages,#chatMessages,.chat-messages,[data-chat-messages],.chatBody,.chat-body,.conversation,.messagesWrap')||document.querySelector('main')}
function fixScroll(h){if(!h)return;h.style.setProperty('overflow-y','auto','important');h.style.setProperty('overflow-x','hidden','important');h.style.setProperty('padding-bottom','150px','important');h.style.setProperty('touch-action','pan-y','important')}
async function search(q,n=6){const headers={'Content-Type':'application/json'};try{const s=(await window.sb?.auth?.getSession())?.data?.session;if(s?.access_token)headers.Authorization='Bearer '+s.access_token}catch{}const r=await fetch(END,{method:'POST',headers,body:JSON.stringify({query:q,maxResults:n})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.details||d.error||'YouTube search failed');return d.videos||[]}
const compact=v=>v.map(x=>({videoId:x.videoId,title:x.title,channelTitle:x.channelTitle,thumbnail:x.thumbnail,url:x.url}));
function marker(q,v){return '[YouTube Search]\n'+JSON.stringify({query:q,videos:compact(v)})}
function parseMarker(s){if(typeof s!=='string'||!s.startsWith('[YouTube Search]\n'))return null;try{return JSON.parse(s.substring('[YouTube Search]\n'.length))}catch{return null}}
function currentHistory(){try{const x=JSON.parse(localStorage.getItem(HIST)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
async function persist(q,v){const content=marker(q,v),a=currentHistory();const last=a[a.length-1];if(!(last?.role==='assistant'&&last?.content===content)){a.push({role:'assistant',content});localStorage.setItem(HIST,JSON.stringify(a))}window.dispatchEvent(new CustomEvent('tivals:youtube-saved',{detail:{query:q}}));try{await window.TivalsCloudHistory?.push?.()}catch(e){console.warn('YouTube cloud save failed',e)}setTimeout(()=>window.TivalsCloudHistory?.push?.(),700)}
function mainCard(v){return '<article style="margin-top:9px;padding:9px;background:#071f3b99;border:1px solid #4c9dff3d;border-radius:14px"><div class="tivals-youtube-player" data-video-id="'+esc(v.videoId)+'" data-thumb="'+esc(v.thumbnail)+'" style="position:relative;width:100%;aspect-ratio:16/9;border-radius:10px;overflow:hidden;background:#000"><img src="'+esc(v.thumbnail)+'" alt="'+esc(v.title)+'" style="width:100%;height:100%;object-fit:cover;pointer-events:none"><button type="button" data-youtube-play="'+esc(v.videoId)+'" style="position:absolute;inset:0;margin:auto;width:60px;height:44px;border:0;border-radius:12px;background:#ff0033;color:white;font-size:25px">▶</button></div><div style="font-weight:750;font-size:14px;margin:8px 2px 2px">'+esc(v.title)+'</div><div style="font-size:12px;opacity:.68">'+esc(v.channelTitle)+'</div></article>'}
function miniCard(v){return '<article style="display:grid;grid-template-columns:108px minmax(0,1fr);gap:8px;align-items:center;margin-top:8px;padding:7px;background:#071f3b80;border:1px solid #4c9dff2e;border-radius:12px"><button type="button" data-youtube-play-mini="'+esc(v.videoId)+'" data-thumb="'+esc(v.thumbnail)+'" style="position:relative;width:108px;aspect-ratio:16/9;padding:0;border:0;border-radius:8px;overflow:hidden;background:#000"><img src="'+esc(v.thumbnail)+'" style="width:100%;height:100%;object-fit:cover;pointer-events:none"><span style="position:absolute;inset:0;margin:auto;width:38px;height:28px;line-height:28px;border-radius:8px;background:#ff0033;color:white">▶</span></button><div><div style="font-weight:700;font-size:13px;line-height:1.25">'+esc(v.title)+'</div><div style="font-size:11px;opacity:.65;margin-top:3px">'+esc(v.channelTitle)+'</div></div></article>'}
function block(v,q){const d=document.createElement('div');d.className='tivals-youtube-results';d.dataset.youtubeQuery=q;d.style.cssText='margin-top:8px;width:100%;box-sizing:border-box;touch-action:pan-y';d.innerHTML='<div style="font-size:14px;line-height:1.4">I found videos for <strong>'+esc(q)+'</strong>. You can watch them here.</div>'+(v[0]?mainCard(v[0]):'')+(v.length>1?'<details style="margin-top:7px"><summary style="cursor:pointer;color:#79b8ff;font-size:13px;font-weight:700;padding:6px 2px">More videos ('+Math.min(v.length-1,4)+')</summary>'+v.slice(1,5).map(miniCard).join('')+'</details>':'');return d}
function assistantRows(h){return [...h.querySelectorAll('.assistant-message,.message.assistant,.assistant,.ai-message,.bot-message,[data-role="assistant"]')]}
function insertAfterUserSearch(media,q,h){const rows=[...h.querySelectorAll('.message,.user-message,.assistant-message,.ai-message,.bot-message,[data-role]')];for(let i=rows.length-1;i>=0;i--){const text=(rows[i].innerText||'').toLowerCase();if(text.includes(q.toLowerCase())&&(rows[i].matches('.user-message,[data-role="user"]')||rows[i].classList.contains('user'))){rows[i].insertAdjacentElement('afterend',media);return true}}return false}
function wrapMedia(media){const row=document.createElement('div');row.className='tivals-youtube-message assistant-message';row.dataset.role='assistant';row.style.cssText='display:flex;gap:9px;width:100%;max-width:700px;margin:12px auto;padding:0 10px;box-sizing:border-box';row.innerHTML='<div style="flex:0 0 36px;width:36px;height:36px;border-radius:50%;overflow:hidden"><img src="./app-icon.svg" style="width:100%;height:100%"></div><div style="min-width:0;width:100%;max-width:560px"></div>';row.lastElementChild.appendChild(media);return row}
function render(v,q,placement=true){const h=host(),media=block(v,q),row=wrapMedia(media);if(placement&&h){if(!insertAfterUserSearch(row,q,h))h.appendChild(row)}return row}
function queryFrom(t){t=String(t||'').trim();if(!t)return null;const explicit=/\byoutube\b/i.test(t),intent=/\b(video|videos|tutorial|tutorials|watch|play|lesson|lessons|course|courses)\b/i.test(t)&&/\b(find|search|show|give|recommend|look|watch|play|learn|learning)\b/i.test(t);if(!explicit&&!intent)return null;return t.replace(/\b(on|from|in)\s+youtube\b/ig,' ').replace(/\byoutube\b/ig,' ').replace(/\b(find|search|show|give|recommend|display|look|watch|play|me|some|videos?|tutorials?|channels?|about|for|results?)\b/ig,' ').replace(/\s+/g,' ').trim()||null}
async function run(q){const h=host();if(!h)return false;fixScroll(h);const slot=document.createElement('div');slot.className='tivals-youtube-slot';slot.style.cssText='margin:8px 12px;padding:8px;opacity:.72';slot.textContent='Tivals AI is searching YouTube…';h.appendChild(slot);try{const v=await search(q);if(!v.length){slot.textContent='No matching videos found.';return true}const row=render(v,q,false);slot.replaceWith(row);await persist(q,v);fixScroll(h);row.scrollIntoView({block:'nearest',behavior:'smooth'});return true}catch(e){slot.textContent='YouTube search error: '+e.message;return true}}
function restore(){const h=host();if(!h)return;fixScroll(h);h.querySelectorAll('.tivals-youtube-message').forEach(x=>x.remove());const a=currentHistory();for(const m of a){const x=parseMarker(m?.content);if(x?.query&&Array.isArray(x.videos))render(x.videos,x.query,true)}}
function inputNear(el){const r=el?.closest?.('form,.composer,.inputArea,.input-area,.chat-input,.prompt-box')||document;return r.querySelector?.('textarea,input[type="text"]')||document.querySelector('textarea,input[type="text"]')}
function playIn(p,id,thumb){p.dataset.videoId=id;p.dataset.thumb=thumb;p.innerHTML='<iframe title="YouTube video" style="display:block;width:100%;height:100%;border:0" src="https://www.youtube-nocookie.com/embed/'+encodeURIComponent(id)+'?autoplay=1&playsinline=1" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe><button type="button" data-youtube-close style="position:absolute;top:6px;right:6px;z-index:4;border:0;border-radius:50%;background:#000c;color:white;width:32px;height:32px;font-size:19px">×</button>'}
async function intercept(e,i){const q=queryFrom(i?.value);if(!q)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.();i.value='';i.dispatchEvent(new Event('input',{bubbles:true}));await run(q)}
document.addEventListener('click',e=>{const mini=e.target.closest?.('[data-youtube-play-mini]');if(mini){e.preventDefault();const root=mini.closest('.tivals-youtube-results'),main=root?.querySelector('.tivals-youtube-player');if(main){playIn(main,mini.dataset.youtubePlayMini,mini.dataset.thumb);main.scrollIntoView({block:'center',behavior:'smooth'})}return}const play=e.target.closest?.('[data-youtube-play]');if(play){e.preventDefault();const p=play.closest('.tivals-youtube-player');playIn(p,play.dataset.youtubePlay,p.dataset.thumb);return}const close=e.target.closest?.('[data-youtube-close]');if(close){e.preventDefault();const p=close.closest('.tivals-youtube-player'),id=p.dataset.videoId,thumb=p.dataset.thumb;p.innerHTML='<img src="'+esc(thumb)+'" style="width:100%;height:100%;object-fit:cover;pointer-events:none"><button type="button" data-youtube-play="'+esc(id)+'" style="position:absolute;inset:0;margin:auto;width:60px;height:44px;border:0;border-radius:12px;background:#ff0033;color:white;font-size:25px">▶</button>';return}const b=e.target.closest?.('button');if(b){const i=inputNear(b);if(queryFrom(i?.value))intercept(e,i)}},true);document.addEventListener('submit',e=>{const i=inputNear(e.target);if(queryFrom(i?.value))intercept(e,i)},true);document.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&queryFrom(e.target?.value))intercept(e,e.target)},true);
window.addEventListener('tivals:cloud-history-loaded',()=>setTimeout(restore,150));window.addEventListener('storage',e=>{if(e.key===HIST)setTimeout(restore,80)});setTimeout(restore,900);window.TivalsYouTube={search,render,run,restore,queryFrom};})();