/* Tivals AI — YouTube search as a native-looking assistant response with durable history. */
(()=>{const END='https://kxuszpixwfecawdeqkrx.supabase.co/functions/v1/youtube-search',HIST='tivals-ai-history';
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function host(){return document.querySelector('#messages,.messages,#chatMessages,.chat-messages,[data-chat-messages],.chatBody,.chat-body,.conversation,.messagesWrap')||document.querySelector('main')}
function fixScroll(h){if(!h)return;h.style.setProperty('overflow-y','auto','important');h.style.setProperty('overflow-x','hidden','important');h.style.setProperty('-webkit-overflow-scrolling','touch');h.style.setProperty('touch-action','pan-y','important')}
async function search(q,n=6){const headers={'Content-Type':'application/json'};try{const s=(await window.sb?.auth?.getSession())?.data?.session;if(s?.access_token)headers.Authorization='Bearer '+s.access_token}catch{}const r=await fetch(END,{method:'POST',headers,body:JSON.stringify({query:q,maxResults:n})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.details||d.error||'YouTube search failed');return d.videos||[]}
function marker(q,v){return '[YouTube Search]\n'+JSON.stringify({query:q,videos:v.map(x=>({videoId:x.videoId,title:x.title,channelTitle:x.channelTitle,thumbnail:x.thumbnail,url:x.url}))})}
function parseMarker(s){if(typeof s!=='string'||!s.startsWith('[YouTube Search]\n'))return null;try{return JSON.parse(s.slice(17))}catch{return null}}
function persist(q,v){try{let a=JSON.parse(localStorage.getItem(HIST)||'[]');if(!Array.isArray(a))a=[];a.push({role:'user',content:'Search YouTube for '+q},{role:'assistant',content:marker(q,v)});localStorage.setItem(HIST,JSON.stringify(a));setTimeout(()=>window.TivalsCloudHistory?.push?.(),50)}catch(e){console.warn('YouTube history save failed',e)}}
function videoCard(v){return '<article class="tivals-youtube-card" style="margin:10px 0;padding:10px;background:rgba(8,31,59,.62);border:1px solid rgba(76,157,255,.24);border-radius:14px;overflow:hidden;touch-action:pan-y"><div class="tivals-youtube-player" data-video-id="'+esc(v.videoId)+'" data-thumb="'+esc(v.thumbnail)+'" style="position:relative;width:100%;aspect-ratio:16/9;border-radius:11px;overflow:hidden;background:#000;touch-action:pan-y"><img src="'+esc(v.thumbnail)+'" alt="'+esc(v.title)+'" loading="lazy" style="display:block;width:100%;height:100%;object-fit:cover;pointer-events:none"><button type="button" data-youtube-play="'+esc(v.videoId)+'" aria-label="Play in chat" style="position:absolute;inset:0;margin:auto;width:64px;height:46px;border:0;border-radius:13px;background:#ff0033;color:#fff;font-size:27px">▶</button></div><div style="font-weight:750;font-size:15px;margin:9px 2px 3px;line-height:1.3">'+esc(v.title)+'</div><div style="font-size:12px;opacity:.7;margin:0 2px 7px">'+esc(v.channelTitle)+'</div><a href="'+esc(v.url)+'" target="_blank" rel="noopener" style="font-size:13px;color:#65adff;text-decoration:none;font-weight:700">Open in YouTube ↗</a></article>'}
function render(videos,q){const row=document.createElement('div');row.className='tivals-youtube-results tivals-ai-assistant-row';row.dataset.youtubeQuery=q;row.style.cssText='display:flex;align-items:flex-start;gap:10px;width:100%;max-width:760px;margin:12px auto;padding:0 10px;box-sizing:border-box;touch-action:pan-y';row.innerHTML='<div class="tivals-ai-result-avatar" style="flex:0 0 38px;width:38px;height:38px;border-radius:50%;overflow:hidden;background:#08294d;border:1px solid #278cff66;box-shadow:0 0 14px #1689ff33"><img src="./app-icon.svg" alt="Tivals AI" style="width:100%;height:100%;object-fit:cover"></div><div class="tivals-ai-result-bubble" style="min-width:0;max-width:min(620px,calc(100vw - 78px));padding:12px;background:rgba(12,42,76,.78);border:1px solid rgba(73,151,242,.25);border-radius:6px 18px 18px 18px;box-sizing:border-box"><div style="font-size:12px;font-weight:800;color:#6db5ff;margin-bottom:5px">Tivals AI</div><div style="font-size:15px;line-height:1.45;margin-bottom:8px">I found these YouTube videos for <strong>'+esc(q)+'</strong>. Tap a video to watch it here in the chat.</div>'+videos.map(videoCard).join('')+'</div>';return row}
function queryFrom(text){text=String(text||'').trim();if(!/youtube/i.test(text))return null;let q=text.replace(/\b(on|from|in)\s+youtube\b/ig,' ').replace(/\byoutube\b/ig,' ').replace(/\b(find|search|show|give|recommend|display|play|me|some|videos?|channels?|about|for|results?)\b/ig,' ').replace(/\s+/g,' ').trim();return q||null}
async function run(q){const h=host();if(!h)return false;fixScroll(h);const loading=document.createElement('div');loading.style.cssText='margin:12px;padding:12px;opacity:.75';loading.textContent='Tivals AI is searching YouTube…';h.appendChild(loading);try{const v=await search(q);if(!v.length){loading.textContent='Tivals AI could not find matching YouTube videos.';return true}const r=render(v,q);loading.replaceWith(r);persist(q,v);fixScroll(h);r.scrollIntoView({block:'nearest',behavior:'smooth'});return true}catch(e){loading.textContent='YouTube search error: '+e.message;return true}}
function restore(){const h=host();if(!h)return;fixScroll(h);let a=[];try{a=JSON.parse(localStorage.getItem(HIST)||'[]')}catch{}if(!Array.isArray(a))return;const saved=a.map(m=>parseMarker(m?.content)).filter(Boolean),existing=new Set([...h.querySelectorAll('.tivals-youtube-results')].map(x=>x.dataset.youtubeQuery));for(const x of saved){if(x?.query&&Array.isArray(x.videos)&&!existing.has(x.query)){h.appendChild(render(x.videos,x.query));existing.add(x.query)}}}
function inputNear(el){const root=el?.closest?.('form,.composer,.inputArea,.input-area,.chat-input,.prompt-box')||document;return root.querySelector?.('textarea,input[type="text"]')||document.querySelector('textarea,input[type="text"]')}
async function intercept(e,inp){const q=queryFrom(inp?.value);if(!q)return false;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.();inp.value='';inp.dispatchEvent(new Event('input',{bubbles:true}));await run(q);return true}
document.addEventListener('click',e=>{const play=e.target.closest?.('[data-youtube-play]');if(play){e.preventDefault();e.stopPropagation();const id=play.dataset.youtubePlay,p=play.closest('.tivals-youtube-player');if(!id||!p)return;const thumb=p.dataset.thumb||'';p.innerHTML='<iframe title="YouTube video" style="display:block;width:100%;height:100%;border:0" src="https://www.youtube-nocookie.com/embed/'+encodeURIComponent(id)+'?autoplay=1&playsinline=1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><button type="button" data-youtube-close aria-label="Close video" style="position:absolute;top:7px;right:7px;z-index:4;border:0;border-radius:50%;background:#000c;color:#fff;width:34px;height:34px;font-size:20px">×</button>';p.dataset.thumb=thumb;return}const close=e.target.closest?.('[data-youtube-close]');if(close){e.preventDefault();e.stopPropagation();const p=close.closest('.tivals-youtube-player'),id=p?.dataset.videoId,thumb=p?.dataset.thumb;if(!p||!id)return;p.innerHTML='<img src="'+esc(thumb)+'" alt="YouTube thumbnail" style="display:block;width:100%;height:100%;object-fit:cover;pointer-events:none"><button type="button" data-youtube-play="'+esc(id)+'" aria-label="Play in chat" style="position:absolute;inset:0;margin:auto;width:64px;height:46px;border:0;border-radius:13px;background:#ff0033;color:#fff;font-size:27px">▶</button>';return}const b=e.target.closest?.('button');if(!b)return;const inp=inputNear(b);if(queryFrom(inp?.value))intercept(e,inp)},true);
document.addEventListener('submit',e=>{const inp=inputNear(e.target);if(queryFrom(inp?.value))intercept(e,inp)},true);document.addEventListener('keydown',e=>{if(e.key!=='Enter'||e.shiftKey||!(e.target instanceof HTMLTextAreaElement||e.target?.matches?.('input[type="text"]')))return;if(queryFrom(e.target.value))intercept(e,e.target)},true);window.addEventListener('tivals:cloud-history-loaded',()=>setTimeout(restore,100));window.addEventListener('storage',e=>{if(e.key===HIST)setTimeout(restore,50)});setTimeout(restore,700);setTimeout(restore,1800);window.TivalsYouTube={search,render,run,restore,queryFrom};})();