/* Tivals AI — YouTube search, durable chat persistence and mobile-safe result cards. */
(()=>{const END='https://kxuszpixwfecawdeqkrx.supabase.co/functions/v1/youtube-search',HIST='tivals-ai-history';
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function host(){return document.querySelector('#messages,.messages,#chatMessages,.chat-messages,[data-chat-messages],.chatBody,.chat-body,.conversation,.messagesWrap')||document.querySelector('main')}
function fixScroll(h){if(!h)return;h.style.setProperty('overflow-y','auto','important');h.style.setProperty('overflow-x','hidden','important');h.style.setProperty('-webkit-overflow-scrolling','touch');h.style.setProperty('overscroll-behavior-y','contain');h.style.setProperty('touch-action','pan-y','important');h.querySelectorAll('.tivals-youtube-results,.tivals-youtube-card,.tivals-youtube-player').forEach(x=>x.style.setProperty('touch-action','pan-y','important'))}
async function search(q,n=6){const headers={'Content-Type':'application/json'};try{const s=(await window.sb?.auth?.getSession())?.data?.session;if(s?.access_token)headers.Authorization='Bearer '+s.access_token}catch{}const r=await fetch(END,{method:'POST',headers,body:JSON.stringify({query:q,maxResults:n})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.details||d.error||'YouTube search failed');return d.videos||[]}
function marker(q,v){return '[YouTube Search]\n'+JSON.stringify({query:q,videos:v.map(x=>({videoId:x.videoId,title:x.title,channelTitle:x.channelTitle,thumbnail:x.thumbnail,url:x.url}))})}
function parseMarker(s){if(typeof s!=='string'||!s.startsWith('[YouTube Search]\n'))return null;try{return JSON.parse(s.slice(17))}catch{return null}}
function persist(q,v){try{let a=JSON.parse(localStorage.getItem(HIST)||'[]');if(!Array.isArray(a))a=[];a.push({role:'user',content:'Search YouTube for '+q},{role:'assistant',content:marker(q,v)});localStorage.setItem(HIST,JSON.stringify(a));window.dispatchEvent(new CustomEvent('tivals:youtube-saved',{detail:{query:q,videos:v}}));setTimeout(()=>window.TivalsCloudHistory?.push?.(),50)}catch(e){console.warn('YouTube history save failed',e)}}
function render(videos,q){const box=document.createElement('section');box.className='tivals-youtube-results';box.dataset.youtubeQuery=q;box.style.cssText='width:100%;max-width:760px;margin:12px auto;touch-action:pan-y;overscroll-behavior-y:contain';box.innerHTML='<div style="font-weight:800;font-size:18px;margin:8px 0 12px">YouTube videos for “'+esc(q)+'”</div>'+videos.map(v=>'<article class="tivals-youtube-card" style="margin:14px 0;padding:12px;background:rgba(9,35,66,.72);border:1px solid rgba(69,160,255,.3);border-radius:16px;overflow:hidden;touch-action:pan-y"><a href="'+esc(v.url)+'" target="_blank" rel="noopener" class="tivals-youtube-player" style="position:relative;display:block;width:100%;aspect-ratio:16/9;border-radius:12px;overflow:hidden;background:#000;touch-action:pan-y"><img src="'+esc(v.thumbnail)+'" alt="'+esc(v.title)+'" loading="lazy" style="display:block;width:100%;height:100%;object-fit:cover;pointer-events:none"><span style="position:absolute;inset:0;margin:auto;width:72px;height:52px;border-radius:14px;background:#ff0033;color:#fff;font-size:30px;line-height:52px;text-align:center;pointer-events:none">▶</span></a><div style="font-weight:750;font-size:16px;margin:10px 2px 4px">'+esc(v.title)+'</div><div style="font-size:13px;opacity:.72;margin:0 2px 8px">'+esc(v.channelTitle)+'</div><a href="'+esc(v.url)+'" target="_blank" rel="noopener" style="display:inline-block;padding:8px 12px;border-radius:10px;background:#1677ff;color:#fff;text-decoration:none;font-weight:700">Open in YouTube</a></article>').join('');return box}
function queryFrom(text){text=String(text||'').trim();if(!/youtube/i.test(text))return null;let q=text.replace(/\b(on|from|in)\s+youtube\b/ig,' ').replace(/\byoutube\b/ig,' ').replace(/\b(find|search|show|give|recommend|display|play|me|some|videos?|channels?|about|for|results?)\b/ig,' ').replace(/\s+/g,' ').trim();return q||null}
async function run(q){const h=host();if(!h)return false;fixScroll(h);const loading=document.createElement('div');loading.textContent='Searching YouTube…';loading.style.cssText='padding:14px;opacity:.75;touch-action:pan-y';h.appendChild(loading);try{const v=await search(q);if(!v.length){loading.textContent='No YouTube videos found.';return true}const card=render(v,q);loading.replaceWith(card);fixScroll(h);persist(q,v);card.scrollIntoView({block:'nearest',behavior:'smooth'});return true}catch(e){loading.textContent='YouTube search error: '+e.message;return true}}
function restore(){const h=host();if(!h)return;fixScroll(h);let a=[];try{a=JSON.parse(localStorage.getItem(HIST)||'[]')}catch{}if(!Array.isArray(a))return;const saved=a.map(m=>parseMarker(m?.content)).filter(Boolean);if(!saved.length)return;const existing=new Set([...h.querySelectorAll('.tivals-youtube-results')].map(x=>x.dataset.youtubeQuery));for(const x of saved){if(!x?.query||!Array.isArray(x.videos)||existing.has(x.query))continue;h.appendChild(render(x.videos,x.query));existing.add(x.query)}fixScroll(h)}
function inputNear(el){const root=el?.closest?.('form,.composer,.inputArea,.input-area,.chat-input,.prompt-box')||document;return root.querySelector?.('textarea,input[type="text"]')||document.querySelector('textarea,input[type="text"]')}
async function intercept(e,inp){const q=queryFrom(inp?.value);if(!q)return false;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.();inp.value='';inp.dispatchEvent(new Event('input',{bubbles:true}));await run(q);return true}
document.addEventListener('submit',e=>{const inp=inputNear(e.target);if(queryFrom(inp?.value))intercept(e,inp)},true);document.addEventListener('click',e=>{const b=e.target.closest?.('button');if(!b)return;const inp=inputNear(b);if(queryFrom(inp?.value))intercept(e,inp)},true);document.addEventListener('keydown',e=>{if(e.key!=='Enter'||e.shiftKey||!(e.target instanceof HTMLTextAreaElement||e.target?.matches?.('input[type="text"]')))return;if(queryFrom(e.target.value))intercept(e,e.target)},true);
window.addEventListener('tivals:cloud-history-loaded',()=>setTimeout(restore,100));window.addEventListener('storage',e=>{if(e.key===HIST)setTimeout(restore,50)});setTimeout(restore,700);setTimeout(restore,1800);window.TivalsYouTube={search,render,run,restore,queryFrom};})();