/* Tivals AI radio hub. Direct verified streams play in-app; other stations retain broadcaster fallback pages. */
(()=>{
const stations=[
{name:'Phalaphala FM',lang:'Tshivenda',stream:'https://playerservices.streamtheworld.com/api/livestream-redirect/PHALAPHALAAAC.aac?dist=tivalsai',url:'https://www.phalaphalafm.co.za/phalaphalafm/'},
{name:'Thobela FM',lang:'Sepedi',stream:'https://playerservices.streamtheworld.com/api/livestream-redirect/THOBELAAAC_SC?dist=tivalsai',url:'https://www.thobelafm.co.za/thobelafm/livestreams/'},
{name:'METRO FM',lang:'Music / English',url:'https://www.metrofm.co.za/metro-fm/listen-live/'},
{name:'Ukhozi FM',lang:'isiZulu',stream:'https://playerservices.streamtheworld.com/api/livestream-redirect/UKHOZIFMAAC_SC?dist=tivalsai',url:'https://www.ukhozifm.co.za/'},
{name:'5FM',lang:'Youth / Music',url:'https://listen.5fm.co.za/'},{name:'Munghana Lonene FM',lang:'itsonga',url:'https://listen.munghanalonenefm.co.za/listenmunghanalonenefm/'},{name:'Motsweding FM',lang:'Setswana',url:'https://listen.motswedingfm.co.za/listenmotswedingfm/'},
{name:'Lesedi FM',lang:'Sesotho',stream:'https://playerservices.streamtheworld.com/api/livestream-redirect/LESEDIAAC_SC?dist=tivalsai',url:'https://www.lesedifm.co.za/lesedifm/'},
{name:'SAfm',lang:'News / Talk',url:'https://www.safm.co.za/'},{name:'Radio 2000',lang:'Music / Talk',url:'https://www.radio2000.co.za/'},{name:'Good Hope FM',lang:'Music',url:'https://www.goodhopefm.co.za/'},{name:'Umhlobo Wenene FM',lang:'isiXhosa',url:'https://www.umhlobowenenefm.co.za/'},{name:'Ligwalagwala FM',lang:'siSwati',url:'https://www.ligwalagwalafm.co.za/'},{name:'Ikwekwezi FM',lang:'isiNdebele',url:'https://www.ikwekwezifm.co.za/'},{name:'Lotus FM',lang:'Indian South African',url:'https://www.lotusfm.co.za/'},{name:'RSG',lang:'Afrikaans',url:'https://www.rsg.co.za/'},
{name:'Jacaranda FM',lang:'English / Afrikaans',stream:'https://edge.iono.fm/xice/jacarandafm_live_medium.aac',url:'https://www.jacarandafm.com/'},{name:'Power 98.7',lang:'English / Talk',stream:'https://edge.iono.fm/xice/65_medium.aac',url:'https://www.power987.co.za/'},{name:'KFM 94.5',lang:'English / Music',stream:'https://playerservices.streamtheworld.com/api/livestream-redirect/KFM.mp3?dist=tivalsai',url:'https://kfm.co.za/'}];
let audio=new Audio(),current=null;audio.preload='none';
const css=`#tivalsRadio{position:fixed;inset:0;z-index:10050;background:#061a31;color:#f7fbff;display:none;overflow:auto;font-family:inherit}.tr-head{position:sticky;top:0;z-index:2;background:#092542;padding:16px;display:flex;align-items:center;gap:12px;border-bottom:1px solid #24517b}.tr-head h2{margin:0;flex:1}.tr-close{border:1px solid #3d6b96;background:#102f50;color:white;border-radius:12px;padding:10px 14px;font-size:20px}.tr-search{display:block;width:calc(100% - 32px);box-sizing:border-box;margin:16px;padding:13px 15px;border-radius:14px;border:1px solid #315e87;background:#0b2744;color:white;font-size:16px}.tr-grid{padding:0 16px 130px;display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.tr-card{border:1px solid #214b70;background:#0a233e;border-radius:16px;padding:15px}.tr-card h3{margin:0 0 5px}.tr-card small{opacity:.72}.tr-play{margin-top:13px;width:100%;border:0;border-radius:12px;padding:12px;background:#1677d2;color:white;font-weight:700}.tr-now{position:fixed;z-index:10051;left:12px;right:12px;bottom:12px;background:#0d2d4c;border:1px solid #376b96;border-radius:18px;padding:12px;display:none;align-items:center;gap:10px}.tr-now strong{flex:1}.tr-now button{border:0;border-radius:10px;padding:10px 13px;background:#1677d2;color:#fff}.tr-note{padding:0 16px 14px;opacity:.75;font-size:13px}`;
function fallback(s){const w=window.open(s.url,'_blank','noopener,noreferrer');if(!w)location.href=s.url}
async function play(s){if(!s.stream){fallback(s);return}try{audio.pause();audio.src=s.stream;audio.load();current=s;await audio.play();updateNow();render(document.querySelector('#tivalsRadioSearch')?.value||'')}catch(e){console.warn('Radio stream failed',e);fallback(s)}}
function stop(){audio.pause();audio.removeAttribute('src');audio.load();current=null;updateNow();render(document.querySelector('#tivalsRadioSearch')?.value||'')}
function updateNow(){const n=document.querySelector('#tivalsRadioNow');if(!n)return;n.style.display=current?'flex':'none';const t=n.querySelector('strong');if(t)t.textContent=current?'📻 '+current.name:''}
function render(q=''){const root=document.querySelector('#tivalsRadioGrid');if(!root)return;const x=q.trim().toLowerCase();root.innerHTML='';stations.filter(s=>!x||`${s.name} ${s.lang}`.toLowerCase().includes(x)).forEach(s=>{const c=document.createElement('div');c.className='tr-card';const h=document.createElement('h3');h.textContent=s.name;const sm=document.createElement('small');sm.textContent=s.lang+(s.stream?' · In-app live':' · Broadcaster player');const b=document.createElement('button');b.className='tr-play';b.textContent=current?.name===s.name&&!audio.paused?'⏹ Stop':'▶ Listen Live';b.onclick=()=>current?.name===s.name&&!audio.paused?stop():play(s);c.append(h,sm,b);root.appendChild(c)})}
function open(){const p=document.querySelector('#tivalsRadio');if(p){p.style.display='block';render()}}function close(){const p=document.querySelector('#tivalsRadio');if(p)p.style.display='none'}
function boot(){if(document.querySelector('#tivalsRadio'))return;const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);const p=document.createElement('section');p.id='tivalsRadio';p.innerHTML='<div class="tr-head"><h2>📻 Live Radio</h2><button class="tr-close">×</button></div><input class="tr-search" id="tivalsRadioSearch" placeholder="Search stations or language…"><div class="tr-note">Verified direct streams play inside Tivals AI. Stations without a verified browser-safe stream open the broadcaster player.</div><div class="tr-grid" id="tivalsRadioGrid"></div><div class="tr-now" id="tivalsRadioNow"><strong></strong><button id="trPause">⏯</button><button id="trStop">⏹</button></div>';document.body.appendChild(p);p.querySelector('.tr-close').onclick=close;p.querySelector('#tivalsRadioSearch').oninput=e=>render(e.target.value);p.querySelector('#trPause').onclick=()=>audio.paused?audio.play():audio.pause();p.querySelector('#trStop').onclick=stop;render();const host=document.querySelector('.sideTools')||document.querySelector('.tools')||document.querySelector('nav');if(host&&!document.querySelector('#tivalsRadioButton')){const b=document.createElement('button');b.type='button';b.id='tivalsRadioButton';b.className=host.classList.contains('sideTools')?'sideTool':'toolBtn';b.textContent='📻 Radio';b.onclick=open;host.appendChild(b)}}
audio.onplay=()=>{updateNow();render(document.querySelector('#tivalsRadioSearch')?.value||'')};audio.onpause=()=>{updateNow();render(document.querySelector('#tivalsRadioSearch')?.value||'')};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.TivalsRadio={open,close,stations,play,stop,audio};
})();