plugins { id 'com.android.application' }

android {
    namespace 'com.tivalsdeveloper.tivalsai'
    compileSdk 36

    defaultConfig {
        applicationId 'com.tivalsdeveloper.tivalsai'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '3.0.0'
    }
}

dependencies {
}
