plugins { id 'com.android.application' }

android {
    namespace 'com.tivalsdeveloper.tivalsai'
    compileSdk 36
    defaultConfig {
        applicationId 'com.tivalsdeveloper.tivalsai'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.6.2'
}
